### ISSUE TITLE
http 500 errors

### ISSUE THREAD

**Issue by taylorshaulis** [adsabs/solr-service#19]
The solr-service is generating occasional http 500 errors on the api microservice

example error

`ERROR   10474 [07/20/2017 16:35:53]:    
            Request:     GET /search/query
            IP:          131.142.156.212
            Agent:       macos | safari 603.2.4
            Raw Agent:   Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4
            Oauth2:      <oauthlib.Request url="https://api.adsabs.harvard.edu/v1/search/query?facet=true&facet.field=property&facet.limit=20&facet.mincount=1&facet.offset=0&facet.query=property%3Arefereed&fl=id&q=bibstem%3A%22ApJS%22&rows=1&sort=date%20desc%2C%20bibcode%20desc", http_method="GET", headers="{u'Origin': u'https://ui.adsabs.harvard.edu', u'Accept-Language': u'en-us', u'Accept-Encoding': u'gzip, deflate', u'X-Forwarded-Port': u'443', u'X-Forwarded-For': u'131.142.156.212, 10.1.0.53', u'Accept': u'application/json, text/javascript, */*; q=0.01', u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4', u'Host': u'api.adsabs.harvard.edu', u'X-Forwarded-Proto': u'https', u'Referer': u'https://ui.adsabs.harvard.edu/', u'X-Real-Ip': u'10.1.0.53', u'Content-Type': u'application/x-www-form-urlencoded', u'Authorization': u'Bearer:INMsJ4h0ggzNv8wHLpjnUqlwTFKlhQEorBAt2j4Z'}", body="{}">
            
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauthlib/provider/oauth2.py", line 540, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_ratelimiter/__init__.py", line 174, in rate_limited
    current_limit, per)
  File "/usr/local/lib/python2.7/dist-packages/flask_ratelimiter/backends/simpleredis_backend.py", line 55, in update
    current = min(self.pipeline.execute()[0], limit)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2626, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2535, in _execute_transaction
    raise ResponseError("Wrong number of response items from "
ResponseError: Wrong number of response items from pipeline execution`

**Comment by taylorshaulis** [comment]
There was a patch deployed to sandbox to try to resolve this error.  Now I am seeing a different error message

**Comment by taylorshaulis** [comment]
First is a json of the http event.  Second and 3rd are from the solr searcher app logs.

`{
  "_index": "cwl-2017.07.24",
  "_type": "staging-adsws-gunicorn-access",
  "_id": "33471215991586020652271376012156254658015744843460837410",
  "_score": null,
  "_source": {
    "referer": "https://devui.adsabs.harvard.edu/",
    "cookie": "-",
    "request_method": "GET",
    "authorization": "Bearer:GeIq3Ij7EsYxFPT927kdwhCNNdkFfLTn2v3OD59l",
    "response_length": "291",
    "protocol": "HTTP/1.1",
    "request_time": 63223,
    "URLpath": "/search/query",
    "host": "65.112.8.197, 10.1.3.216",
    "moment_this_happened": "2017-07-24T13:00:34.179Z",
    "status_line": "GET /v1/search/query?fl=title%2Cbibcode%2Cauthor%2Ckeyword%2Cpub%2Caff%2Cvolume%2Cyear%2Clinks_data%2C%5Bcitations%5D%2Cproperty%2Cpubdate%2Cabstract&q=references(bibcode%3A1959ApJ...130..507P)&rows=25&sort=first_author%20asc&start=0 HTTP/1.1",
    "query_string": "fl=title%2Cbibcode%2Cauthor%2Ckeyword%2Cpub%2Caff%2Cvolume%2Cyear%2Clinks_data%2C%5Bcitations%5D%2Cproperty%2Cpubdate%2Cabstract&q=references(bibcode%3A1959ApJ...130..507P)&rows=25&sort=first_author%20asc&start=0",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0",
    "status": 500,
    "@id": "33471215991586020652271376012156254658015744843460837410",
    "@timestamp": "2017-07-24T13:00:34.179Z",
    "@message": "\"65.112.8.197, 10.1.3.216\" \"[24/Jul/2017:13:00:33 +0000]\" \"GET /v1/search/query?fl=title%2Cbibcode%2Cauthor%2Ckeyword%2Cpub%2Caff%2Cvolume%2Cyear%2Clinks_data%2C%5Bcitations%5D%2Cproperty%2Cpubdate%2Cabstract&q=references(bibcode%3A1959ApJ...130..507P)&rows=25&sort=first_author%20asc&start=0 HTTP/1.1\" \"GET\" \"/search/query\" \"fl=title%2Cbibcode%2Cauthor%2Ckeyword%2Cpub%2Caff%2Cvolume%2Cyear%2Clinks_data%2C%5Bcitations%5D%2Cproperty%2Cpubdate%2Cabstract&q=references(bibcode%3A1959ApJ...130..507P)&rows=25&sort=first_author%20asc&start=0\" \"HTTP/1.1\" \"500\" \"291\" \"https://devui.adsabs.harvard.edu/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0\" \"63223\" \"-\" \"Bearer:GeIq3Ij7EsYxFPT927kdwhCNNdkFfLTn2v3OD59l\"",
    "@owner": "084981688622",
    "@log_group": "staging-adsws-gunicorn-access",
    "@log_stream": "1963a3bcc289-gunicorn-access"
  },
  "fields": {
    "@timestamp": [
      1500901234179
    ]
  },
  "sort": [
    1500901234179
  ]
}

ERROR   5436 [07/24/2017 13:00:33]:     
            Request:     GET /search/query
            IP:          172.17.0.1
            Agent:       macos | firefox 54.0
            Raw Agent:   Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0
            Oauth2:      <oauthlib.Request url="http://devapi.adsabs.harvard.edu/v1/search/query?fl=title%2Cbibcode%2Cauthor%2Ckeyword%2Cpub%2Caff%2Cvolume%2Cyear%2Clinks_data%2C%5Bcitations%5D%2Cproperty%2Cpubdate%2Cabstract&q=citations(b
ibcode%3A1959ApJ...130..507P)&rows=25&sort=date%20desc&start=0", http_method="GET", headers="{u'Origin': u'https://devui.adsabs.harvard.edu', u'Accept-Language': u'en-US,en;q=0.5', u'Accept-Encoding': u'gzip, deflate, br', u'X-Forwarded-Po
rt': u'443', u'X-Forwarded-For': u'65.112.8.197, 10.1.3.216', u'Prefer': u'safe', u'Accept': u'application/json, text/javascript, */*; q=0.01', u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/
54.0', u'Host': u'devapi.adsabs.harvard.edu', u'X-Forwarded-Proto': u'https', u'Referer': u'https://devui.adsabs.harvard.edu/', u'X-Real-Ip': u'10.1.3.216', u'Content-Type': u'application/x-www-form-urlencoded', u'Authorization': u'Bearer:
GeIq3Ij7EsYxFPT927kdwhCNNdkFfLTn2v3OD59l'}", body="{}">
            
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauthlib/provider/oauth2.py", line 540, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_ratelimiter/__init__.py", line 177, in rate_limited
    current_limit, per)
  File "/usr/local/lib/python2.7/dist-packages/flask_ratelimiter/backends/simpleredis_backend.py", line 55, in update
    current = min(self.pipeline.execute()[0], limit)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2626, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2549, in _execute_transaction
    r = self.response_callbacks[command_name](r, **options)
ValueError: invalid literal for int() with base 10: 'Q'
ERROR   5436 [07/24/2017 13:00:33]:     
            Request:     GET /search/query
            IP:          172.17.0.1
            Agent:       macos | firefox 54.0
            Raw Agent:   Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0
            Oauth2:      <oauthlib.Request url="http://devapi.adsabs.harvard.edu/v1/search/query?fl=title%2Cbibcode%2Cauthor%2Ckeyword%2Cpub%2Caff%2Cvolume%2Cyear%2Clinks_data%2C%5Bcitations%5D%2Cproperty%2Cpubdate%2Cabstract&q=references(bibcode%3A1959ApJ...130..507P)&rows=25&sort=first_author%20asc&start=0", http_method="GET", headers="{u'Origin': u'https://devui.adsabs.harvard.edu', u'Accept-Language': u'en-US,en;q=0.5', u'Accept-Encoding': u'gzip, deflate, br', u'X-Forwarded-Port': u'443', u'X-Forwarded-For': u'65.112.8.197, 10.1.3.216', u'Prefer': u'safe', u'Accept': u'application/json, text/javascript, */*; q=0.01', u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0', u'Host': u'devapi.adsabs.harvard.edu', u'X-Forwarded-Proto': u'https', u'Referer': u'https://devui.adsabs.harvard.edu/', u'X-Real-Ip': u'10.1.3.216', u'Content-Type': u'application/x-www-form-urlencoded', u'Authorization': u'Bearer:GeIq3Ij7EsYxFPT927kdwhCNNdkFfLTn2v3OD59l'}", body="{}">



ERROR   5436 [07/24/2017 13:00:33]:     
            Request:     GET /search/query
            IP:          172.17.0.1
            Agent:       macos | firefox 54.0
            Raw Agent:   Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0
            Oauth2:      <oauthlib.Request url="http://devapi.adsabs.harvard.edu/v1/search/query?fl=title%2Cbibcode%2Cauthor%2Ckeyword%2Cpub%2Caff%2Cvolume%2Cyear%2Clinks_data%2C%5Bcitations%5D%2Cproperty%2Cpubdate%2Cabstract&q=references(bibcode%3A1959ApJ...130..507P)&rows=25&sort=first_author%20asc&start=0", http_method="GET", headers="{u'Origin': u'https://devui.adsabs.harvard.edu', u'Accept-Language': u'en-US,en;q=0.5', u'Accept-Encoding': u'gzip, deflate, br', u'X-Forwarded-Port': u'443', u'X-Forwarded-For': u'65.112.8.197, 10.1.3.216', u'Prefer': u'safe', u'Accept': u'application/json, text/javascript, */*; q=0.01', u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0', u'Host': u'devapi.adsabs.harvard.edu', u'X-Forwarded-Proto': u'https', u'Referer': u'https://devui.adsabs.harvard.edu/', u'X-Real-Ip': u'10.1.3.216', u'Content-Type': u'application/x-www-form-urlencoded', u'Authorization': u'Bearer:GeIq3Ij7EsYxFPT927kdwhCNNdkFfLTn2v3OD59l'}", body="{}">
            
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauthlib/provider/oauth2.py", line 540, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_ratelimiter/__init__.py", line 177, in rate_limited
    current_limit, per)
  File "/usr/local/lib/python2.7/dist-packages/flask_ratelimiter/backends/simpleredis_backend.py", line 55, in update
    current = min(self.pipeline.execute()[0], limit)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2626, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2503, in _execute_transaction
    self.parse_response(connection, '_')
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2584, in parse_response
    self, connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 246, in read_response
    (str(byte), str(response)))
InvalidResponse: Protocol Error: ^@, ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@+OK



`
